### ISSUE TITLE
There is no 'sudo' on FreeBSD

### ISSUE THREAD

**Issue by megapearl** [rubenverhoef/iocage-plugin-dsmr#1]
iocage is the 'docker' variant of FreeBSD, in your post_install.sh script you use the command 'sudo'.
There is no sudo on FreeBSD variants (like FreeNAS en TrueNAS) so the script does not work.

**Comment by rubenverhoef** [comment]
It will work because `sudo` will be installed during `iocage` jail creation:

https://github.com/rubenverhoef/freenas-jails/blob/master/dsmr/dsmr.json#L12

**Comment by megapearl** [comment]
Ah okay, I did it manually, never saw your other repo https://github.com/rubenverhoef/freenas-jails/blob/master/dsmr/dsmr.json#L12
